lesson3/app16_animal/config/routes.rb
Rails.application.routes.draw do
  root 'animals#index'

  resources :animals
end

lesson3/app16_animal/app/models/animal.rb
class Animal < ApplicationRecord
end

lesson3/app16_animal/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :current_animal, only: [:show, :edit, :update, :destroy]

  def index
    @animals = Animal.all
  end

  def show
  end

  def new
    @animal = Animal.new
  end

  def create
    animal = Animal.new(animal_params)
    if animal.save
      redirect_to animal
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @animal.update(animal_params)
      redirect_to @animal
    else
      render :edit
    end
  end

  def destroy
    @animal.delete
    redirect_to animals_path
  end

  private

  def animal_params
    params.require(:animal).permit(:name)
  end

  def current_animal
    @animal = Animal.find(params[:id])
  end
end

lesson3/app16_animal/app/views/animals/_form.html.erb
<%= form_for @animal do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />
  <%= f.submit %>
<% end %>

lesson3/app16_animal/app/views/animals/edit.html.erb
<h1>Edit animal ID <%= @animal.id %></h1>

<%= render 'form' %>

<%= link_to 'Back', animals_path %>

lesson3/app16_animal/app/views/animals/index.html.erb
<h1>List of animals</h1>

<%= link_to 'Create new animal', new_animal_path %>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
  </tr>
  <% @animals.each do |animal| %>
    <tr>
      <td><%= animal.id %></td>
      <td><%= animal.name %></td>
      <td><%= link_to 'Show', animal %></td>
      <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
      <td><%= link_to 'Delete', animal, method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

lesson3/app16_animal/app/views/animals/new.html.erb
<h1>Create new animal</h1>

<%= render 'form' %>

<%= link_to 'Back', animals_path %>

lesson3/app16_animal/app/views/animals/show.html.erb
<h1>Animal ID <%= @animal.id %></h1>

<p>
  Name: <%= @animal.name %>
</p>

<%= link_to 'Back', animals_path %>