lesson5/config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  get 'sign_up', to: 'users#new'
  get 'sign_in', to: 'sessions#new', as: :sign_in
  get 'log_out', to: 'sessions#destroy', as: :log_out
  post 'create', to: 'sessions#create', as: :sessions

  resources :users do
    resources :posts
    resource :profile, only: [:show, :edit, :update]
  end

  namespace :admin do
    resources :users, only: [:index, :update, :destroy]
    resources :posts, only: [:index, :destroy]
    resources :categories, except: :show
  end

  resources :comments, only: [:create, :destroy]
end

lesson5/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

lesson5/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts
  has_one  :profile
end

lesson5/app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :admin_only
  before_action :current_resource, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.delete
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def current_resource
    @category = Category.find(params[:id])
  end
end

lesson5/app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  before_action :admin_only

  def index
    @posts = Post.all
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end
end

lesson5/app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :admin_only
  before_action :current_resource, only: [:update, :destroy]

  def index
    @users = User.all
  end

  def update
    @user.update(admin: params[:admin])
    redirect_to admin_users_path
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def current_resource
    @user = User.find(params[:id])
  end
end

lesson5/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  private

  def admin_only
    redirect_to current_user unless current_user.admin
  end
end

lesson5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def require_user
    redirect_to root_path unless current_user
  end
end

lesson5/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user
  before_action :current_user_resource
  before_action :current_resource, only: [:show, :edit, :update, :destroy]
  before_action :require_owner

  def index
    @posts = @user.posts.paginate(page: params[:page])
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = @user.posts.build(post_params)
    if @post.save
      pry
      redirect_to [@user, @post]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to [@user, @post]
    else
      render :edit
    end
  end

  def destroy
    @post.delete
    redirect_to user_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :image, :category_ids)
  end

  def current_resource
    @post = @user.posts.find(params[:id])
  end

  def current_user_resource
    @user = User.find(params[:user_id])
  end

  def require_owner
    redirect_to root_path unless current_user == @user
  end
end

lesson5/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :current_user_resource
  before_action :current_resource

  def show
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to [@user, @profile]
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :avatar, :gender, :birthday)
  end

  def current_resource
    @profile = @user.profile
  end

  def current_user_resource
    @user = User.find(params[:user_id])
  end
end

lesson5/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

lesson5/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show]
  before_action :current_resource, only: [:show]

  def show
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      user.create_profile
      session[:user_id] = user.id
      redirect_to user
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def current_resource
    @user = User.find(params[:id])
  end
end

lesson5/app/views/admin/users/index.haml
%h1 Users

%table
  %thead
    %tr
      %th ID
      %th Email
  %tbody
    - @users.each do |user|
      %tr
        %td = user.id
        %td = user.email
        - if user.admin
          %td = link_to 'Disable admin', admin_user_path(user, admin: false),
                        method: :patch
        - else
          %td = link_to 'Enable admin', admin_user_path(user, admin: true),
                        method: :patch
        %td = link_to 'Delete', admin_user_path(user), method: :delete

lesson5/app/views/posts/_form.haml
= form_for [@user, @post] do |f|
  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :text
    = f.text_field :text
  %p
    = f.label :image
    = f.file_field :image
  %p
    = f.submit

lesson5/app/views/posts/_form.slim
= form_for [@user, @post] do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :text
    = f.text_field :text
  p
    = f.label :image
    = f.file_field :image
  p
    = f.label :categories
    br
    = f.collection_check_boxes :categories, Category.all, :id, :name
  p
    = f.submit

lesson5/app/views/posts/_posts.haml
%table
  %thead
    %tr
      %td
      %td Title
  %tbody
    - @posts.each do |post|
      %tr
        %td = image_tag post.image, size: '200x100'
        %td = post.title
        %td = link_to 'Show', [@user, post]
        %td = link_to 'Edit', edit_user_post_path(@user, post)
        %td = link_to 'Delete', [@user, post], method: :delete

lesson5/app/views/posts/edit.haml
%h2 Edit post
= render 'form'

lesson5/app/views/posts/edit.slim
h2 Edit post
= render 'form'

lesson5/app/views/posts/index.haml
%h2 Posts

- if @posts.present?
  = render 'posts'
  = will_paginate @posts
- else
  You don't have any posts now!

= link_to 'New post', new_user_post_path(@user)

lesson5/app/views/posts/index.slim
h2 Posts

- if @posts.present?
  = render 'posts'
  = will_paginate @posts
- else
  | You don't have any posts now!

= link_to 'New post', new_user_post_path(@user)

lesson5/app/views/posts/new.haml
%h2 New post
= render 'form'

lesson5/app/views/posts/new.slim
h2 New post
= render 'form'

lesson5/app/views/posts/show.haml
%p Title: #{@post.title}
%p Text: #{@post.text}
%p = image_tag @post.image, size: '600x300'
%p = link_to 'Edit', edit_user_post_path(@user, @post)
%p = link_to 'Delete', [@user, @post], method: :delete
%p = link_to 'Back to all posts', user_posts_path(@user)

lesson5/app/views/posts/show.slim
p Title: #{@post.title}

p Text: #{@post.text}

p = image_tag @post.image, size: '600x300'

= render 'shared/comment_form'

h2 Comments:

table
  thead
    tr
      th Text
  tbody
  - @post.comments.each do |comment|
    tr
      td = comment.text

p = link_to 'Edit', edit_user_post_path(@user, @post)

p = link_to 'Delete', [@user, @post], method: :delete

p = link_to 'Back to all posts', user_posts_path(@user)

lesson5/app/views/shared/_comment_form.slim
= form_for @comment do |f|
  p
    = f.label :text
    = f.text_field :text

  p = f.submit 'Add comment'

lesson5/app/views/shared/_header.haml
- if current_user
  %p
    = image_tag current_user.profile.avatar, size: '100x50'
    = current_user.email
    = link_to 'Sign Out', log_out_path
    - if current_user.admin
      = link_to 'Admin panel', admin_users_path

lesson5/app/views/shared/_header.slim
- if current_user
  p
    = image_tag current_user.profile.avatar, size: '100x50'
    = current_user.email
    = link_to 'Sign Out', log_out_path
    - if current_user.admin
      = link_to 'Admin panel', admin_users_path