lesson3/app19_audio/config/routes.rb
Rails.application.routes.draw do
  root 'audios#index'

  resources :audios
end

lesson3/app19_audio/app/models/audio.rb
class Audio < ApplicationRecord
end

lesson3/app19_audio/app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  before_action :current_audio, only: [:show, :edit, :update, :destroy]

  def index
    @audios = Audio.all
  end

  def show
  end

  def new
    @audio = Audio.new
  end

  def create
    audio = Audio.new(audio_params)
    if audio.save
      redirect_to audio
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @audio.update(audio_params)
      redirect_to @audio
    else
      render :edit
    end
  end

  def destroy
    @audio.delete
    redirect_to audios_path
  end

  private

  def audio_params
    params.require(:audio).permit(:title)
  end

  def current_audio
    @audio = Audio.find(params[:id])
  end
end

lesson3/app19_audio/app/views/audios/_form.html.erb
<%= form_for @audio do |f| %>
  <%= f.label :title %><br />
  <%= f.text_field :title %><br />
  <%= f.submit %>
<% end %>

lesson3/app19_audio/app/views/audios/edit.html.erb
<h1>Edit audio ID <%= @audio.id %></h1>

<%= render 'form' %>

<%= link_to 'Back', audios_path %>

lesson3/app19_audio/app/views/audios/index.html.erb
<h1>List of audios</h1>

<%= link_to 'Create new audio', new_audio_path %>

<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
  </tr>
  <% @audios.each do |audio| %>
    <tr>
      <td><%= audio.id %></td>
      <td><%= audio.title %></td>
      <td><%= link_to 'Show', audio %></td>
      <td><%= link_to 'Edit', edit_audio_path(audio) %></td>
      <td><%= link_to 'Delete', audio, method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

lesson3/app19_audio/app/views/audios/new.html.erb
<h1>Create new audio</h1>

<%= render 'form' %>

<%= link_to 'Back', audios_path %>

lesson3/app19_audio/app/views/audios/show.html.erb
<h1>Audio ID <%= @audio.id %></h1>

<p>
  Title: <%= @audio.title %>
</p>

<%= link_to 'Back', audios_path %>